module CodeRay
  module Scanners

    module Scala::BuiltinTypes  # :nodoc:

      #:nocov:
      List = %w[
        Any
        AnyVal
        App
        Array
        Boolean
        Byte
        Char
        Cloneable
        Console
        DelayedInit
        Double
        Dynamic
        Enumeration
        Equals
        FallbackArrayBuilding
        Float
        Function
        Function1
        Function2
        Immutable
        Int
        Long
        MatchError
        Mutable
        None
        NotImplementedError
        NotNull
        Option
        PartialFunction
        Predef
        Product
        Product1
        Product2
        Proxy
        Responder
        ScalaReflectionException
        Serializable
        SerialVersionUID
        Short
        Some
        Specializable
        StringContext
        Symbol
        Tuple1
        Tuple2
        UninitializedError
        UninitializedFieldError
        Unit
        Annotation
        ClassfileAnnotation
        StaticAnnotation
        TypeConstraint
        BeanDescription
        BeanDisplayName
        BeanInfo
        BeanInfoSkip
        BeanProperty
        BooleanBeanProperty
        ScalaBeanInfo
        AbstractIterable
        AbstractIterator
        AbstractMap
        AbstractSeq
        AbstractSet
        AbstractTraversable
        BitSet
        BitSetLike
        BufferedIterator
        CustomParallelizable
        DefaultMap
        GenIterable
        GenIterableLike
        GenMap
        GenMapLike
        GenSeq
        GenSeqLike
        GenSet
        GenSetLike
        GenTraversable
        GenTraversableLike
        GenTraversableOnce
        IndexedSeq
        IndexedSeqLike
        IndexedSeqOptimized
        Iterable
        IterableLike
        IterableProxy
        IterableProxyLike
        IterableView
        IterableViewLike
        Iterator
        JavaConversions
        JavaConverters
        LinearSeq
        LinearSeqLike
        LinearSeqOptimized
        Map
        MapLike
        MapProxy
        MapProxyLike
        Parallel
        Parallelizable
        Searching
        Seq
        SeqLike
        SeqProxy
        SeqProxyLike
        SeqView
        SeqViewLike
        Set
        SetLike
        SetProxy
        SetProxyLike
        SortedMap
        SortedMapLike
        SortedSet
        SortedSetLike
        Traversable
        TraversableLike
        TraversableOnce
        TraversableProxy
        TraversableProxyLike
        TraversableView
        TraversableViewLike
        ViewMkString
        Map
        TrieMap
        DecorateAsJava
        DecorateAsScala
        WrapAsJava
        WrapAsScala
        Wrappers
        AtomicIndexFlag
        BitSetFactory
        CanBuildFrom
        CanCombineFrom
        ClassTagTraversableFactory
        Clearable
        DefaultSignalling
        DelegatedContext
        DelegatedSignalling
        FilterMonadic
        GenericClassTagCompanion
        GenericClassTagTraversableTemplate
        GenericCompanion
        GenericOrderedCompanion
        GenericOrderedTraversableTemplate
        GenericParCompanion
        GenericParMapCompanion
        GenericParMapTemplate
        GenericParTemplate
        GenericSeqCompanion
        GenericSetTemplate
        GenericTraversableTemplate
        GenMapFactory
        GenSeqFactory
        GenSetFactory
        GenTraversableFactory
        Growable
        HasNewBuilder
        HasNewCombiner
        IdleSignalling
        ImmutableMapFactory
        ImmutableSetFactory
        ImmutableSortedMapFactory
        ImmutableSortedSetFactory
        IndexedSeqFactory
        IsSeqLike
        IsTraversableLike
        IsTraversableOnce
        IterableForwarder
        MapFactory
        MutableMapFactory
        MutableSetFactory
        MutableSortedSetFactory
        OrderedTraversableFactory
        ParFactory
        ParMapFactory
        ParSetFactory
        SeqFactory
        SeqForwarder
        SetFactory
        Shrinkable
        Signalling
        Sizing
        SliceInterval
        Sorted
        SortedMapFactory
        SortedSetFactory
        Subtractable
        TaggedDelegatedContext
        TraversableFactory
        TraversableForwarder
        VolatileAbort
        AbstractMap
        BitSet
        DefaultMap
        HashMap
        HashSet
        IndexedSeq
        IntMap
        Iterable
        LinearSeq
        List
        ListMap
        ListSet
        LongMap
        Map
        MapLike
        MapProxy
        Nil
        NumericRange
        PagedSeq
        Queue
        Range
        Seq
        Set
        SetProxy
        SortedMap
        SortedSet
        Stack
        Stream
        StreamIterator
        StreamView
        StreamViewLike
        StringLike
        StringOps
        Traversable
        TreeMap
        TreeSet
        Vector
        VectorBuilder
        VectorIterator
        WrappedString
        AbstractBuffer
        AbstractIterable
        AbstractMap
        AbstractSeq
        AbstractSet
        AnyRefMap
        ArrayBuffer
        ArrayBuilder
        ArrayLike
        ArrayOps
        ArraySeq
        ArrayStack
        BitSet
        Buffer
        BufferLike
        BufferProxy
        Builder
        Cloneable
        DefaultEntry
        DefaultMapModel
        DoubleLinkedList
        DoubleLinkedListLike
        FlatHashTable
        GrowingBuilder
        HashEntry
        HashMap
        HashSet
        HashTable
        History
        ImmutableMapAdaptor
        ImmutableSetAdaptor
        IndexedSeq
        IndexedSeqLike
        IndexedSeqOptimized
        IndexedSeqView
        Iterable
        LazyBuilder
        LinearSeq
        LinkedEntry
        LinkedHashMap
        LinkedHashSet
        LinkedList
        LinkedListLike
        ListBuffer
        ListMap
        LongMap
        Map
        MapBuilder
        MapLike
        MapProxy
        MultiMap
        MutableList
        ObservableBuffer
        ObservableMap
        ObservableSet
        OpenHashMap
        PriorityQueue
        PriorityQueueProxy
        Publisher
        Queue
        QueueProxy
        ResizableArray
        RevertibleHistory
        Seq
        SeqLike
        Set
        SetBuilder
        SetLike
        SetProxy
        SortedSet
        Stack
        StackProxy
        StringBuilder
        Subscriber
        SynchronizedBuffer
        SynchronizedMap
        SynchronizedPriorityQueue
        SynchronizedQueue
        SynchronizedSet
        SynchronizedStack
        Traversable
        TreeSet
        Undoable
        UnrolledBuffer
        WeakHashMap
        WrappedArray
        WrappedArrayBuilder
        AdaptiveWorkStealingForkJoinTasks
        AdaptiveWorkStealingTasks
        AdaptiveWorkStealingThreadPoolTasks
        CollectionsHaveToParArray
        Combiner
        CombinerFactory
        CompositeThrowable
        ExecutionContextTasks
        ExecutionContextTaskSupport
        FactoryOps
        ForkJoinTasks
        ForkJoinTaskSupport
        FutureThreadPoolTasks
        HavingForkJoinPool
        IterableSplitter
        ParIterable
        ParIterableLike
        ParMap
        ParMapLike
        ParSeq
        ParSeqLike
        ParSet
        ParSetLike
        PreciseSplitter
        SeqSplitter
        Splitter
        Task
        Tasks
        TaskSupport
        ThreadPoolTasks
        ThreadPoolTaskSupport
        ThrowableOps
        TraversableOps
        HashSetCombiner
        ParHashMap
        ParHashSet
        ParIterable
        ParMap
        ParRange
        ParSeq
        ParSet
        ParVector
        LazyCombiner
        ParArray
        ParFlatHashTable
        ParHashMap
        ParHashSet
        ParHashTable
        ParIterable
        ParMap
        ParMapLike
        ParSeq
        ParSet
        ParSetLike
        ParTrieMap
        ResizableParArrayCombiner
        UnrolledParArrayCombiner
        End
        Include
        Index
        Location
        Message
        NoLo
        Remove
        Reset
        Script
        Scriptable
        Start
        Update
        Platform
        Await
        Awaitable
        BlockContext
        CanAwait
        Channel
        DelayedLazyVal
        ExecutionContext
        ExecutionContextExecutor
        ExecutionContextExecutorService
        Future
        JavaConversions
        Lock
        OnCompleteRunnable
        Promise
        SyncChannel
        SyncVar
        Deadline
        DoubleMult
        Duration
        DurationConversions
        DurationDouble
        DurationInt
        DurationLong
        FiniteDuration
        IntMult
        LongMult
        AnsiColor
        BufferedSource
        Codec
        LowPriorityCodecImplicits
        Source
        StdIn
        BigDecimal
        BigInt
        Equiv
        Fractional
        Integral
        LowPriorityEquiv
        LowPriorityOrderingImplicits
        Numeric
        Ordered
        Ordering
        PartiallyOrdered
        PartialOrdering
        ScalaNumericAnyConversions
        ScalaNumericConversions
        PhantomReference
        Reference
        ReferenceQueue
        ReferenceWrapper
        SoftReference
        WeakReference
        AnyValManifest
        ClassManifestDeprecatedApis
        ClassManifestFactory
        ClassTag
        Manifest
        ManifestFactory
        NameTransformer
        NoManifest
        OptManifest
        AbstractFunction0
        AbstractFunction1
        AbstractFunction2
        AbstractPartialFunction
        ArrayCharSequence
        Boxed
        FractionalProxy
        IntegralProxy
        NonLocalReturnControl
        Nothing$
        Null$
        OrderedProxy
        RangedProxy
        RichBoolean
        RichByte
        RichChar
        RichDouble
        RichException
        RichFloat
        RichInt
        RichLong
        RichShort
        ScalaNumberProxy
        ScalaRunTime
        ScalaWholeNumberProxy
        SeqCharSequence
        StringAdd
        StringFormat
        Tuple2Zipped
        Tuple3Zipped
        ZippedTraversable2
        ZippedTraversable3
        BooleanProp
        Prop
        ShutdownHookThread
        SystemProperties
        BasicIO
        FileProcessLogger
        Process
        ProcessBuilder
        ProcessCreation
        ProcessImplicits
        ProcessIO
        ProcessLogger
        DocBreak
        DocCons
        DocGroup
        DocNest
        DocNil
        DocText
        Document
        DynamicVariable
        Either
        Failure
        Left
        MurmurHash
        Properties
        Random
        Right
        Sorting
        Success
        Try
        Breaks
        ControlThrowable
        Exception
        NonFatal
        NoStackTrace
        TailCalls
        ByteswapHashing
        Hashing
        MurmurHash3
        Regex
        UnanchoredRegex
      ]
      #:nocov:

    end

  end
end
